<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\EncashmentRequest;
use App\Models\MembersEncashmentRequest;
use App\Library\DataTables;

/**
 * @group Members/E-Wallet
 *
 */
class WalletController extends Controller
{
    const MINIMUM_REQUEST_AMOUNT = 500;
    
    /**
     * Display encashment request form
     * 
     */
    public function index()
    {
        $member = Auth::user();
        $pickupcenters = DB::table('pickup_centers')->select(['code', 'description'])->whereNull('deleted_at')->orderBy('sequence')->get();
        
        return view('wallet-form', ['member' => $member, 'minimum_req' => self::MINIMUM_REQUEST_AMOUNT, 'pickupcenters' => $pickupcenters]);
    }
    

    /**
     * Process encashment request
     * 
     * @queryParam source string required
     * Wallet source. Example:Direct Referral
     * 
     * @queryParam amount string required
     * Requested amount. Example:1000
     * 
     * @queryParam req_type string required
     * Payment type. Example: Cheque
     * 
     * @queryParam name string required
     * Member's Fullname. Example Jon Snow
     * 
     * @queryParam mobile string required
     * Member's contact no. Example: 09091232456
     * 
     * @queryParam password string required
     * Member's password
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function postEncashment(EncashmentRequest $request)
    {
        try
        {
            DB::beginTransaction();
            
            if(Auth::user()->has_credits) {
                throw new \Exception('You still have credit balance to settle. Please settle the amount thru your pofile page.');
            }
            
            $data = $request->only('source', 'amount', 
                'pickup_center', 'firstname', 'middlename', 'lastname', 'address1', 'address2',
                'city', 'state', 'country', 'zip', 'mobile', 'email');
            $data['member_id'] = Auth::id();
            
            MembersEncashmentRequest::create($data);
            
            DB::commit();
                    
            return redirect(route('wallet.history'))
                    ->with('status-success', 'Your encashment request has been submitted');
            
        } catch (\Exception $ex) {
            DB::rollback();
            
            return redirect()->back()
                    ->with('status-failed', $ex->getMessage())
                    ->withInput($request->input());
        }
    }
    
    public function history()
    {
        $member = Auth::user();
        
        return view('wallet-history', ['member'=> $member]);
    }
    
    
    /**
     * Display the list of encashment requests
     *
     * @queryParam request array required 
     * JSON request generated by DataTable
     * 
     * @queryParam id integer required 
     * The id of the logged in member. Example: 5
     * 
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function historydata(Request $request, $id)
    {        
        $tablecols = [
            0 => 'id',
            1 => 'created_at',
            2 => 'pickup_center',
            3 => 'amount',
            4 => 'firstname|lastname',
            5 => 'mobile',
            6 => 'tracking_no',
            7 => 'status',
        ];
        
        $filteredmodel = DB::table('members_encashment_requests')
                                ->where('member_id', $id)
                                ->select(DB::raw("amount, 
                                                pickup_center, 
                                                firstname,
                                                lastname,
                                                mobile,
                                                tracking_no,
                                                status,
                                                created_at,
                                                id")
                            );
        
        if($request->has('status') && !empty($request->status)) {
            $filteredmodel->where('status', $request->status);
        }
        
        if($request->has('start_date') && !empty($request->start_date)) {        
            if($request->has('end_date') && !empty($request->end_date && $request->start_date != $request->end_date)) {
                $filteredmodel->whereBetween('created_at', [$request->start_date, $request->end_date . ' 23:59:00']);
            } else {
                $filteredmodel->whereDate('created_at', $request->start_date);
            }
        }

        $modelcnt = $filteredmodel->count();

        $data = DataTables::DataTableFiltersNormalSearch($filteredmodel, $request, $tablecols, $hasValue, $totalFiltered);

        return response(['data'=> $data,
            'draw' => $request->draw,
            'recordsTotal' => ($hasValue)? $data->count(): $modelcnt,
            'recordsFiltered' => ($hasValue)? $totalFiltered: $modelcnt], 200);
    }
}
